  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - my-network

  formation-service:
    build: ./formation-service
    container_name: formation-service
    depends_on:
      - mysql-service
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    networks:
      - my-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - mysql-service
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    networks:
      - my-network
